/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import clases.cl_productos_clasificacion;
import clases.cl_varios;
import javax.swing.JOptionPane;
import casa_biblia.frm_principal;
import clases.cl_productos_sub_clasificacion;
import java.awt.event.KeyEvent;

/**
 *
 * @author luis
 */
public class frm_ver_clasificacion_productos extends javax.swing.JInternalFrame {

    cl_varios c_varios = new cl_varios();
    cl_productos_clasificacion c_clasificacion = new cl_productos_clasificacion();
    cl_productos_sub_clasificacion c_subclasificacion = new cl_productos_sub_clasificacion();

    int fila_seleccionada;
    int fila_subclasificacion;

    /**
     * Creates new form frm_ver_usuarios
     */
    public frm_ver_clasificacion_productos() {
        initComponents();
        c_clasificacion.mostrar(t_clasificacion);
    }

    private void activar_botones() {
        btn_modificar.setEnabled(true);
        btn_ver_sub.setEnabled(true);
    }

    private void desactivar_botones() {
        btn_modificar.setEnabled(false);
        btn_ver_sub.setEnabled(false);
    }

    private void activar_campos() {
        txt_reg_nombre.setEnabled(true);
        btn_j_grabar.setEnabled(true);
    }

    private void reiniciar_campos() {
        txt_reg_nombre.setEnabled(true);
        btn_j_grabar.setEnabled(false);
        txt_reg_nombre.setText("");
        txt_reg_nombre.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_reg_clasificacion = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        txt_reg_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_reg_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btn_j_grabar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btn_j_cerrar = new javax.swing.JButton();
        jd_ver_sub_clasificacion = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_nom_clasificacion = new javax.swing.JTextField();
        txt_nom_subclasificacion = new javax.swing.JTextField();
        jToolBar3 = new javax.swing.JToolBar();
        btn_sub_nuevo = new javax.swing.JButton();
        btn_sub_grabar = new javax.swing.JButton();
        btn_sub_modificar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btn_sub_salir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_subclasificacion = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_clasificacion = new javax.swing.JTable();
        jToolBar2 = new javax.swing.JToolBar();
        btn_agregar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btn_ver_sub = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btn_cerrar = new javax.swing.JButton();

        jd_reg_clasificacion.setTitle("Registrar Usuario");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Generales"));

        txt_reg_id.setEnabled(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Codigo:");

        txt_reg_nombre.setEnabled(false);
        txt_reg_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_reg_nombreKeyPressed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nombre:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_reg_nombre)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_reg_id, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 493, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_reg_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_reg_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jToolBar1.setFloatable(false);
        jToolBar1.setOpaque(false);

        btn_j_grabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/accept.png"))); // NOI18N
        btn_j_grabar.setText("Guardar");
        btn_j_grabar.setEnabled(false);
        btn_j_grabar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_j_grabar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn_j_grabar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_j_grabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_j_grabarActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_j_grabar);
        jToolBar1.add(jSeparator1);

        btn_j_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cross.png"))); // NOI18N
        btn_j_cerrar.setText("Cerrar");
        btn_j_cerrar.setFocusable(false);
        btn_j_cerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_j_cerrar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn_j_cerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_j_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_j_cerrarActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_j_cerrar);

        javax.swing.GroupLayout jd_reg_clasificacionLayout = new javax.swing.GroupLayout(jd_reg_clasificacion.getContentPane());
        jd_reg_clasificacion.getContentPane().setLayout(jd_reg_clasificacionLayout);
        jd_reg_clasificacionLayout.setHorizontalGroup(
            jd_reg_clasificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_reg_clasificacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_reg_clasificacionLayout.setVerticalGroup(
            jd_reg_clasificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_reg_clasificacionLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jd_ver_sub_clasificacion.setTitle("Ver Sub Clasificacion");

        jLabel2.setText("Clasificacion:");

        jLabel4.setText("Sub Clasificacion:");

        txt_nom_clasificacion.setEnabled(false);

        txt_nom_subclasificacion.setEnabled(false);
        txt_nom_subclasificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nom_subclasificacionKeyPressed(evt);
            }
        });

        jToolBar3.setFloatable(false);

        btn_sub_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        btn_sub_nuevo.setText("Nuevo");
        btn_sub_nuevo.setFocusable(false);
        btn_sub_nuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_sub_nuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_sub_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sub_nuevoActionPerformed(evt);
            }
        });
        jToolBar3.add(btn_sub_nuevo);

        btn_sub_grabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/accept.png"))); // NOI18N
        btn_sub_grabar.setText("Grabar");
        btn_sub_grabar.setEnabled(false);
        btn_sub_grabar.setFocusable(false);
        btn_sub_grabar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_sub_grabar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_sub_grabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sub_grabarActionPerformed(evt);
            }
        });
        jToolBar3.add(btn_sub_grabar);

        btn_sub_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/application_edit.png"))); // NOI18N
        btn_sub_modificar.setText("Modificar");
        btn_sub_modificar.setEnabled(false);
        btn_sub_modificar.setFocusable(false);
        btn_sub_modificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_sub_modificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_sub_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sub_modificarActionPerformed(evt);
            }
        });
        jToolBar3.add(btn_sub_modificar);
        jToolBar3.add(jSeparator4);

        btn_sub_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cross.png"))); // NOI18N
        btn_sub_salir.setText("Salir");
        btn_sub_salir.setFocusable(false);
        btn_sub_salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_sub_salir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_sub_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sub_salirActionPerformed(evt);
            }
        });
        jToolBar3.add(btn_sub_salir);

        t_subclasificacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        t_subclasificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_subclasificacionMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(t_subclasificacion);

        javax.swing.GroupLayout jd_ver_sub_clasificacionLayout = new javax.swing.GroupLayout(jd_ver_sub_clasificacion.getContentPane());
        jd_ver_sub_clasificacion.getContentPane().setLayout(jd_ver_sub_clasificacionLayout);
        jd_ver_sub_clasificacionLayout.setHorizontalGroup(
            jd_ver_sub_clasificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(jd_ver_sub_clasificacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_ver_sub_clasificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ver_sub_clasificacionLayout.createSequentialGroup()
                        .addGroup(jd_ver_sub_clasificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jd_ver_sub_clasificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nom_clasificacion)
                            .addComponent(txt_nom_subclasificacion)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jd_ver_sub_clasificacionLayout.setVerticalGroup(
            jd_ver_sub_clasificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ver_sub_clasificacionLayout.createSequentialGroup()
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_ver_sub_clasificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nom_clasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_ver_sub_clasificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nom_subclasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );

        setTitle("Ver Clasificacion de Productos");

        t_clasificacion.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        t_clasificacion.setGridColor(new java.awt.Color(255, 255, 255));
        t_clasificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_clasificacionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(t_clasificacion);
        if (t_clasificacion.getColumnModel().getColumnCount() > 0) {
            t_clasificacion.getColumnModel().getColumn(0).setPreferredWidth(30);
            t_clasificacion.getColumnModel().getColumn(1).setPreferredWidth(100);
            t_clasificacion.getColumnModel().getColumn(2).setPreferredWidth(350);
            t_clasificacion.getColumnModel().getColumn(3).setPreferredWidth(150);
            t_clasificacion.getColumnModel().getColumn(4).setPreferredWidth(80);
        }

        jToolBar2.setFloatable(false);
        jToolBar2.setOpaque(false);

        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        btn_agregar.setText("Agregar");
        btn_agregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_agregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        jToolBar2.add(btn_agregar);

        btn_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/application_edit.png"))); // NOI18N
        btn_modificar.setText("Modificar");
        btn_modificar.setEnabled(false);
        btn_modificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_modificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        jToolBar2.add(btn_modificar);
        jToolBar2.add(jSeparator2);

        btn_ver_sub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/blog.png"))); // NOI18N
        btn_ver_sub.setText("Sub Clasificacion");
        btn_ver_sub.setEnabled(false);
        btn_ver_sub.setFocusable(false);
        btn_ver_sub.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_ver_sub.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_ver_sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ver_subActionPerformed(evt);
            }
        });
        jToolBar2.add(btn_ver_sub);
        jToolBar2.add(jSeparator3);

        btn_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cross.png"))); // NOI18N
        btn_cerrar.setText("Cerrar");
        btn_cerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_cerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });
        jToolBar2.add(btn_cerrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        jd_reg_clasificacion.setModal(true);
        jd_reg_clasificacion.setSize(721, 239);
        jd_reg_clasificacion.setLocationRelativeTo(null);
        c_clasificacion.setId_clasificacion(0);
        reiniciar_campos();
        jd_reg_clasificacion.setVisible(true);
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_j_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_j_cerrarActionPerformed
        jd_reg_clasificacion.dispose();
    }//GEN-LAST:event_btn_j_cerrarActionPerformed

    private void t_clasificacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_clasificacionMouseClicked
        if (evt.getClickCount() == 2) {
            fila_seleccionada = t_clasificacion.getSelectedRow();
            activar_botones();
        }
    }//GEN-LAST:event_t_clasificacionMouseClicked

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        desactivar_botones();
        c_clasificacion.setId_clasificacion(Integer.parseInt(t_clasificacion.getValueAt(fila_seleccionada, 0).toString()));
        c_clasificacion.obtener_datos();
        txt_reg_nombre.setText(c_clasificacion.getDescripcion());
        txt_reg_id.setText(c_clasificacion.getId_clasificacion() + "");

        jd_reg_clasificacion.setModal(true);
        jd_reg_clasificacion.setSize(721, 239);
        jd_reg_clasificacion.setLocationRelativeTo(null);
        jd_reg_clasificacion.setVisible(true);
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_j_grabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_j_grabarActionPerformed
        c_clasificacion.setDescripcion(txt_reg_nombre.getText());
        if (c_clasificacion.getId_clasificacion() == 0) {
            c_clasificacion.obtener_codigo();
            c_clasificacion.registrar();
        } else {
            c_clasificacion.modificar();
        }

        reiniciar_campos();
        jd_reg_clasificacion.dispose();

        c_clasificacion.mostrar(t_clasificacion);
    }//GEN-LAST:event_btn_j_grabarActionPerformed

    private void txt_reg_nombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_reg_nombreKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_reg_nombre.getText().length() > 0) {
                btn_j_grabar.setEnabled(true);
                btn_j_grabar.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_reg_nombreKeyPressed

    private void reiniciar_subclasificacion() {
        //txt_nom_clasificacion.setText("");
        txt_nom_subclasificacion.setText("");
        txt_nom_subclasificacion.setEnabled(false);
    }

    private void btn_ver_subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ver_subActionPerformed
        desactivar_botones();
        reiniciar_subclasificacion();
        c_subclasificacion.setId_clasificacion(Integer.parseInt(t_clasificacion.getValueAt(fila_seleccionada, 0).toString()));
        txt_nom_clasificacion.setText(t_clasificacion.getValueAt(fila_seleccionada, 1).toString());
        c_subclasificacion.mostrar(t_subclasificacion);

        jd_ver_sub_clasificacion.setModal(true);
        jd_ver_sub_clasificacion.setSize(400, 370);
        jd_ver_sub_clasificacion.setLocationRelativeTo(null);
        jd_ver_sub_clasificacion.setVisible(true);
    }//GEN-LAST:event_btn_ver_subActionPerformed

    private void btn_sub_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sub_salirActionPerformed
        jd_ver_sub_clasificacion.dispose();
    }//GEN-LAST:event_btn_sub_salirActionPerformed

    private void btn_sub_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sub_nuevoActionPerformed
        txt_nom_subclasificacion.setEnabled(true);
        txt_nom_subclasificacion.requestFocus();
    }//GEN-LAST:event_btn_sub_nuevoActionPerformed

    private void txt_nom_subclasificacionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nom_subclasificacionKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_nom_subclasificacion.getText().length() > 0) {
                btn_sub_grabar.setEnabled(true);
                btn_sub_grabar.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_nom_subclasificacionKeyPressed

    private void btn_sub_grabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sub_grabarActionPerformed
        c_subclasificacion.setNombre(txt_nom_subclasificacion.getText());
        if (c_subclasificacion.getId_subclasificacion() == 0) {

            c_subclasificacion.obtener_codigo();
            c_subclasificacion.registrar();
        } else {
            c_subclasificacion.modificar();
        }
        btn_sub_grabar.setEnabled(false);
        btn_sub_nuevo.setEnabled(true);
        reiniciar_subclasificacion();
        c_subclasificacion.mostrar(t_subclasificacion);
    }//GEN-LAST:event_btn_sub_grabarActionPerformed

    private void t_subclasificacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_subclasificacionMouseClicked
        if (evt.getClickCount() == 2) {
            btn_sub_modificar.setEnabled(true);
            fila_subclasificacion = t_subclasificacion.getSelectedRow();
        }
    }//GEN-LAST:event_t_subclasificacionMouseClicked

    private void btn_sub_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sub_modificarActionPerformed
        btn_sub_nuevo.setEnabled(false);
        btn_sub_grabar.setEnabled(true);
        btn_sub_modificar.setEnabled(false);
        txt_nom_subclasificacion.setText(t_subclasificacion.getValueAt(fila_subclasificacion, 1).toString());
        c_subclasificacion.setId_subclasificacion(Integer.parseInt(t_subclasificacion.getValueAt(fila_subclasificacion, 0).toString()));
        txt_nom_subclasificacion.setEnabled(true);
        txt_nom_subclasificacion.requestFocus();
    }//GEN-LAST:event_btn_sub_modificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_j_cerrar;
    private javax.swing.JButton btn_j_grabar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_sub_grabar;
    private javax.swing.JButton btn_sub_modificar;
    private javax.swing.JButton btn_sub_nuevo;
    private javax.swing.JButton btn_sub_salir;
    private javax.swing.JButton btn_ver_sub;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JDialog jd_reg_clasificacion;
    private javax.swing.JDialog jd_ver_sub_clasificacion;
    private javax.swing.JTable t_clasificacion;
    private javax.swing.JTable t_subclasificacion;
    private javax.swing.JTextField txt_nom_clasificacion;
    private javax.swing.JTextField txt_nom_subclasificacion;
    private javax.swing.JTextField txt_reg_id;
    private javax.swing.JTextField txt_reg_nombre;
    // End of variables declaration//GEN-END:variables
}
